# GitHub Pages Configuration
title: "Eiken Grade 4 Study App"
description: "英検4級単語学習アプリ"
baseurl: ""
url: "https://username.github.io"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - GEMINI.md
  - requirements.md
  - "*.csv"
  - "*.txt"